### ISSUE TITLE
On Off reversed

### ISSUE THREAD

**Issue by Geffers** [mrstegeman/chromecast-adapter#5]
Simple one - when using Chromecast add-on the on off options appear to have the reverse effect.  On switches device off and visa versa

Geoff Lane

**Comment by mrstegeman** [comment]
I was unable to reproduce the issue, but I attempted a fix.

I just released version 0.4.2 of the add-on. Please let me know if it helps.

**Comment by Geffers** [comment]
Michael,

I have upgraded to 0.4.2 but still the same issue.

I have two chromecast devices, on both when the add-on shows off both
chromecast are actually on.

If I press the gateway add-on button it brightens, changes to show ON but
my chromecast then  disappears from screen, assume it shuts down.  I didnt
actually know the chromecast could be shut down other that pulling the plug.

Geoff

**Comment by freaktechnik** [comment]
The way it used to work when I had initially implemented this plugin (not sure if that's still accurate) is to treat the screensaver mode of the chromecast as off. If you "turn it on" it will switch to an explicit app. This will, however not lead to something being displayed, the main intention is to enable the CEC/HDMI turn on feature. What the property does not indicate is the power or visibility status of the chromecast on your TV.

**Comment by mrstegeman** [comment]
@freaktechnik I was hoping you'd weigh in. 😄 Yes, that's still accurate. CEC commands are still unavailable.

**Comment by Geffers** [comment]
OK - I shall check that out later, Pi being used for something else at the
moment.  I will report back.

Geoff

**Comment by Geffers** [comment]
OK, checked and understand your explanation now.  The screen displayed when
the chromecast is switched on is actually the same as when VLC is enabled
for streaming but before it actually starts to stream.

Thank you for explanation.

Geoff
